In [17]:
import warnings
warnings.filterwarnings('ignore')
from ReadingFiles.GetFiles import get_files
from Preprocessing.preprocessing import return_data
import tensorflow as tf
tf.get_logger().setLevel('ERROR')
from tuh import TUHDataset


In [18]:
%%time
all_files = get_files("../../data")
print("done")

done
CPU times: user 578 µs, sys: 4.55 ms, total: 5.13 ms
Wall time: 4.85 ms


In [19]:
%%time
data0 = return_data(all_files[0][0])

CPU times: user 285 ms, sys: 46.6 ms, total: 332 ms
Wall time: 333 ms


In [20]:
currDataset = TUHDataset("../../data")

In [21]:
dataset = currDataset.create_dataset(2)

In [22]:
dataset

<_FlatMapDataset element_spec=(TensorSpec(shape=(21, 42001), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.bool, name=None))>

In [23]:
it = iter(dataset)

In [24]:
next(it)

2024-03-29 16:10:55.390155: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-29 16:10:55.390289: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-29 16:10:55.390998: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-29 16:10:55.391111: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-29 16:10:55.392583: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GP

(<tf.Tensor: shape=(21, 42001), dtype=float32, numpy=
 array([[-7.54102439e-06, -1.66449681e-05, -1.78438313e-05, ...,
         -1.26441573e-05, -2.01477342e-05, -1.66809041e-05],
        [-7.41277699e-06, -1.48989084e-05, -1.53635374e-05, ...,
         -1.35287073e-05, -1.86862599e-05, -1.90160481e-05],
        [-4.35191077e-06, -1.11342051e-05, -1.26354244e-05, ...,
         -6.95899462e-06, -1.22344163e-05, -1.09442599e-05],
        ...,
        [-2.09492209e-05, -2.63872407e-05, -2.58358086e-05, ...,
         -2.62140838e-05, -2.71760109e-05, -2.68402109e-05],
        [-1.00322040e-05, -8.01166425e-06, -5.93301456e-06, ...,
         -1.51990653e-05, -1.49265206e-05, -1.25903225e-05],
        [-6.08919545e-05, -5.90313721e-05, -5.65315459e-05, ...,
         -2.90137541e-05, -2.95943191e-05, -3.06763104e-05]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=bool, numpy=False>)

In [27]:
for each in (dataset.repeat().take(3)):
    print(each)

(<tf.Tensor: shape=(21, 42001), dtype=float32, numpy=
array([[-7.54102439e-06, -1.66449681e-05, -1.78438313e-05, ...,
        -1.26441573e-05, -2.01477342e-05, -1.66809041e-05],
       [-7.41277699e-06, -1.48989084e-05, -1.53635374e-05, ...,
        -1.35287073e-05, -1.86862599e-05, -1.90160481e-05],
       [-4.35191077e-06, -1.11342051e-05, -1.26354244e-05, ...,
        -6.95899462e-06, -1.22344163e-05, -1.09442599e-05],
       ...,
       [-2.09492209e-05, -2.63872407e-05, -2.58358086e-05, ...,
        -2.62140838e-05, -2.71760109e-05, -2.68402109e-05],
       [-1.00322040e-05, -8.01166425e-06, -5.93301456e-06, ...,
        -1.51990653e-05, -1.49265206e-05, -1.25903225e-05],
       [-6.08919545e-05, -5.90313721e-05, -5.65315459e-05, ...,
        -2.90137541e-05, -2.95943191e-05, -3.06763104e-05]], dtype=float32)>, <tf.Tensor: shape=(), dtype=bool, numpy=False>)
(<tf.Tensor: shape=(21, 42001), dtype=float32, numpy=
array([[-1.46897264e-05,  5.18213847e-06,  6.32896581e-06, ...,
      

2024-03-29 16:13:51.843306: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [29]:
dataset.repeat().padded_batch(32)

<_PaddedBatchDataset element_spec=(TensorSpec(shape=(None, 21, 42001), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.bool, name=None))>

In [30]:
dataset.repeat()

<_RepeatDataset element_spec=(TensorSpec(shape=(21, 42001), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.bool, name=None))>